//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderEFProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class orderitem
    {
        public int order_id { get; set; }
        public int product_id { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<decimal> total { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual product product { get; set; }
    }
}
